apiVersion: v1
kind: Service
metadata:
  name: stock-monitor
  namespace: stock-monitor
  labels:
    app: stock-monitor
spec:
  type: ClusterIP
  selector:
    app: stock-monitor
  ports:
    - name: http
      port: 80
      targetPort: 8137
